### ISSUE TITLE
A problem in seghead structure.

### ISSUE THREAD

**Issue by FriendChi** [TSY845/UFLDv2_MobileNetV3#2]
Traceback (most recent call last):
F[i](https://github.com/cfzd/Ultra-Fast-Lane-Detection-v2/issues/*datas)le "train.py", line 142, in
train(net, train_loader, loss_dict, optimizer, scheduler,logger, epoch, metric_dict, cfg.dataset)
File "train.py", line 30, in train
loss = calc_loss(loss_dict, results, logger, global_step, epoch)
File "/root/Ultra-Fast-Lane-Detection-v2-master/utils/common.py", line 274, in calc_loss
loss_cur = loss_dict['op']i
File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1174, in forward
return F.cross_entropy(input, target, weight=self.weight,
File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/functional.py", line 3029, in cross_entropy
return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: only batches of spatial targets supported (3D tensors) but got targets of size: : [32, 3, 320, 800]

After my inspection, I found that the model would directly return the output of the seghead structure, and then put it together with its label into the cross_entropy_loss function. However, the key point is that the input required by the cross_entropy_loss function is batch_size*C, and the shapes of the two do not match, so an error occurred. But I don't think your code is at fault, so what's the problem?

**Comment by TSY845** [comment]
To clarify, I did not change this part of the project, so the default settings should work fine. The new UFLDv2 does not use segmentation (which was used in UFLD v1) any longer, but codes remain here.  Please take a look at the UFLDv2 paper.

**Comment by FriendChi** [comment]
Thanks for your answer, my response addressed your concerns and provided clarification.
